# covid-sim travis-ci yml
dist: bionic
language: cpp

matrix:
    include:
    - os: linux
      compiler: gcc

    
install:

before_script:  

addons:
  sonarcloud:
    organization: "192933488s"

  apt:
    packages:
      - cmake-data
      - cmake
      - doxygen
      - doxygen-doc
      - graphviz

script:
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  - sonar-scanner -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cfamily
