name: CI for different Linux distributions

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir build && cd build
        cmake ..
        make
    - name: unit tests
      run: |
        cd build
        ctest -j2 -V -E inttest.*
    - name: regression tests
      run: |
        cd build
        ctest -j2 -V -R inttest.*

  test-in-container:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container_image: ["fedora:latest", "debian:10", "archlinux/base", "ubuntu:bionic", "centos:7", "opensuse/tumbleweed", "alpine:latest"]
    container:
      image: ${{ matrix.container_image }}

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./ci/install_dependencies.sh
    - name: download cmake
      run: |
        wget https://cmake.org/files/v3.17/cmake-3.17.2-Linux-x86_64.tar.gz
        tar xf cmake-3.17.2-Linux-x86_64.tar.gz
        export PATH=$(pwd)/cmake-3.17.2-Linux-x86_64/bin:${PATH}
    - name: build bionic
      run: |
        mkdir build && cd build
        ../cmake-3.17.2-Linux-x86_64/bin/cmake ..
        make
      if: matrix.container_image == 'ubuntu:bionic'
    - name: build others
      run: |
        mkdir build && cd build
        cmake ..
        make
      if: matrix.container_image != 'ubuntu:bionic'
    - name: unit tests
      run: |
        cd build
        ctest -j2 -V -E inttest.*
      if: matrix.container_image != 'centos:7'
    - name: regression tests
      run: |
        cd build
        ctest -j2 -V -R inttest.*
      if: matrix.container_image != 'centos:7'
    - name: unit tests centos
      run: |
        cd build
        ctest3 -j2 -V -E inttest.*
      if: matrix.container_image == 'centos:7'
    - name: regression tests centos
      run: |
        cd build
        ctest3 -j2 -V -R inttest.*
      if: matrix.container_image == 'centos:7'
