name: CI for macOS

on: push

jobs:
  macos-build-and-test:
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./ci/install_macos_dependencies.sh
    - name: build
      run: |
        mkdir build && cd build
        cmake ..
        make
    - name: regression tests
      run: |
        pwd
        ls -l
        make test ARGS="-V"
